
export const clientsData = [
    // Petroleum and Logistics
    { name: "Baraka Petroleum", industry: "Petroleum and Logistics", logo: "/clients/Baraka Petroleum.jpg", country: "Somalia" },
    { name: "Mass Petroleum", industry: "Petroleum and Logistics", logo: "/clients/Mass Petroleum.png", country: "Somalia" },
    { name: "Puntland Petroleum", industry: "Petroleum and Logistics", logo: "/clients/Puntland Petroleum.jpeg", country: "Somalia" },
    { name: "Som Petroleum", industry: "Petroleum and Logistics", logo: "/clients/som petrolium.jpg", country: "Somalia" },
    { name: "Khayrmawaaye Petroleum", industry: "Petroleum and Logistics", logo: "/clients/Khayrmawaaye petroleum.jpeg", country: "Somalia" },
    { name: "Royal Energy", industry: "Petroleum and Logistics", logo: "/clients/Royal energy.png", country: "Somalia" },
    { name: "Tristar Group", industry: "Petroleum and Logistics", logo: "/clients/Tristar Group.png", country: "Somalia" },
    { name: "Trust Energy", industry: "Petroleum and Logistics", logo: "/clients/Trust energy.png", country: "Somalia" },
    { name: "Scope Lubricant", industry: "Petroleum and Logistics", logo: "/clients/scope lubricant energy.png", country: "Somalia" },
    { name: "Azmi Energy SARL", industry: "Petroleum and Logistics", logo: "/clients/Azmi Energy SARL.jpg", country: "Somalia" },
    { name: "Dot Transport", industry: "Petroleum and Logistics", logo: "/clients/Dot Transport.jpeg", country: "Somalia" },
    { name: "Same Logistics", industry: "Petroleum and Logistics", logo: "/clients/Same logistics.jpeg", country: "Somalia" },
    { name: "Som Logistics", industry: "Petroleum and Logistics", logo: "/clients/som logistics.png", country: "Somalia" },
    { name: "Sabar Airline", industry: "Petroleum and Logistics", logo: "/clients/sabar Airline retail.jpg", country: "Somalia" },

    // Construction
    { name: "Albashid Construction", industry: "Construction", logo: "/clients/Albashid construction.png", country: "Somalia" },
    { name: "Amal Construction", industry: "Construction", logo: "/clients/Amal Construction.jpg", country: "Somalia" },
    { name: "Deryeel Construction", industry: "Construction", logo: "/clients/Deryeel construction.png", country: "Somalia" },
    { name: "Dolphin Construction", industry: "Construction", logo: "/clients/Dolphin Construction and Land Surveying.jpg", country: "Somalia" },
    { name: "TTN Construction", industry: "Construction", logo: "/clients/TTN construction.jpg", country: "Somalia" },
    { name: "Real Estate", industry: "Construction", logo: "/clients/real estate.jpg", country: "Somalia" },

    // Manufacturing
    { name: "Al Siha Manufacturing", industry: "Manufacturing", logo: "/clients/Al siha manafucturing.png", country: "Somalia" },
    { name: "Gold Foods", industry: "Manufacturing", logo: "/clients/Gold Foods.png", country: "Somalia" },
    { name: "Horyaal Manufacturing", industry: "Manufacturing", logo: "/clients/Horyaal manufucturing.jpg", country: "Somalia" },
    { name: "Modern Manufacture", industry: "Manufacturing", logo: "/clients/Modern manafucture.jpeg", country: "Somalia" },
    { name: "Manufacturing", industry: "Manufacturing", logo: "/clients/manufucturing.png", country: "Somalia" },
    { name: "Weel Factory", industry: "Manufacturing", logo: "/clients/weel factory.jpeg", country: "Somalia" },
    { name: "Bareeda Factory", industry: "Manufacturing", logo: "/clients/Bareeda factory.jpg", country: "Somalia" },

    // Utility
    { name: "BEC Electricity", industry: "Utility", logo: "/clients/bec electricity.jpg", country: "Somalia" },
    { name: "Genius Water", industry: "Utility", logo: "/clients/genius-watter.jpg", country: "Somalia" },
    { name: "Water Utility", industry: "Utility", logo: "/clients/water utility.jpg", country: "Somalia" },
    { name: "Sool Power", industry: "Utility", logo: "/clients/sool power utility.jpg", country: "Somalia" },
    { name: "Utility", industry: "Utility", logo: "/clients/utility.jpg", country: "Somalia" },

    // Healthcare
    { name: "Arafat Hospital", industry: "Healthcare", logo: "/clients/hospital.jpg", country: "Somalia" },
    { name: "Al Siha Hospital", industry: "Healthcare", logo: "/clients/alsiha hospital.jpg", country: "Somalia" },
    { name: "Aragbila Hospital", industry: "Healthcare", logo: "/clients/Aragbila hospital.png", country: "Somalia" },
    { name: "Heegan Pharma", industry: "Healthcare", logo: "/clients/Heegan Pharma.jpeg", country: "Somalia" },
    { name: "Hoslistic", industry: "Healthcare", logo: "/clients/Hoslistic.jpg", country: "Somalia" },
    { name: "Kaafi Hospital", industry: "Healthcare", logo: "/clients/kaafi hospital.jpg", country: "Somalia" },
    { name: "Manhal Hospital", industry: "Healthcare", logo: "/clients/manhal hospital.png", country: "Somalia" },
    { name: "National Hospital", industry: "Healthcare", logo: "/clients/National Hospital.jpg", country: "Somalia" },
    { name: "Royal Care Hospital", industry: "Healthcare", logo: "/clients/Royal Care Hospital.png", country: "Somalia" },
    { name: "Somali Hospital", industry: "Healthcare", logo: "/clients/somali hospital.jpg", country: "Somalia" },
    { name: "Yaashfiin Hospital", industry: "Healthcare", logo: "/clients/yaashfiin hospital .jpeg", country: "Somalia" },
    { name: "Gaalkacyo Hospital", industry: "Healthcare", logo: "/clients/Gaalkacyo hospital.jpeg", country: "Somalia" },
    { name: "Modern Medical Hospital", industry: "Healthcare", logo: "/clients/modern medical hospital.jpg", country: "Somalia" },
    { name: "Siha Hospital", industry: "Healthcare", logo: "/clients/siha hospital.jpg", country: "Somalia" },
    { name: "Bushra Dental Hospital", industry: "Healthcare", logo: "/clients/bushra dental hospital.png", country: "Somalia" },
    { name: "San Medical Hospital", industry: "Healthcare", logo: "/clients/san medical hospital.png", country: "Somalia" },
    { name: "Tayo San Pharmaceuticals", industry: "Healthcare", logo: "/clients/tayo san pharmacuticals.jpg", country: "Somalia" },

    // Hotel and Cafes
    { name: "Abad Hotel", industry: "Hotel and Cafes", logo: "/clients/Abad Hotel .jpeg", country: "Somalia" },
    { name: "Airport Hotel", industry: "Hotel and Cafes", logo: "/clients/Airport hotel.jpg", country: "Somalia" },
    { name: "Ambassador Hotel", industry: "Hotel and Cafes", logo: "/clients/ambassador hotel.jpg", country: "Somalia" },
    { name: "Bilan Cafe", industry: "Hotel and Cafes", logo: "/clients/bilan cafe.jpg", country: "Somalia" },
    { name: "Baydan Coffee", industry: "Hotel and Cafes", logo: "/clients/baydan coffee.png", country: "Somalia" },
    { name: "Cafe", industry: "Hotel and Cafes", logo: "/clients/cafe.png", country: "Somalia" },
    { name: "Hiil Cafe", industry: "Hotel and Cafes", logo: "/clients/Hiil cafe.png", country: "Somalia" },
    { name: "Jefel Cafe", industry: "Hotel and Cafes", logo: "/clients/jefel cafe.png", country: "Somalia" },
    { name: "Melili Hotel", industry: "Hotel and Cafes", logo: "/clients/melili hotel.png", country: "Somalia" },
    { name: "Cawale Blue Hotel", industry: "Hotel and Cafes", logo: "/clients/cawale blue hotel.png", country: "Somalia" },
    { name: "Jaabir Hotel", industry: "Hotel and Cafes", logo: "/clients/jaabir hotel.jpg", country: "Somalia" },
    { name: "Nugal Hotel", industry: "Hotel and Cafes", logo: "/clients/nugal Hotel.png", country: "Somalia" },

    // Public Sectors
    { name: "Ministry of Finance", industry: "Public Sectors", logo: "/clients/ministry of finance .jpg", country: "Somalia" },
    { name: "Local Ministry Garowe", industry: "Public Sectors", logo: "/clients/local ministry garowe.jpg", country: "Somalia" },
    { name: "Finance SL Government", industry: "Public Sectors", logo: "/clients/finance sl goverment.png", country: "Somalia" },
    { name: "Puntland Government", industry: "Public Sectors", logo: "/clients/puntland goverment.jpg", country: "Somalia" },
    { name: "PL Government", industry: "Public Sectors", logo: "/clients/pl goverment.jpg", country: "Somalia" },
    { name: "PL Election Government", industry: "Public Sectors", logo: "/clients/pl election goverment.jpg", country: "Somalia" },
    { name: "Government", industry: "Public Sectors", logo: "/clients/Goverment.jpg", country: "Somalia" },
    { name: "University of Bosaso", industry: "Public Sectors", logo: "/clients/University of Bosaso.png", country: "Somalia" },
    { name: "University of Peace", industry: "Public Sectors", logo: "/clients/university of peace.png", country: "Somalia" },
    { name: "University", industry: "Public Sectors", logo: "/clients/university.jpg", country: "Somalia" },
    { name: "Buhoodle Institute", industry: "Public Sectors", logo: "/clients/buhoodle institute.jpg", country: "Somalia" },
    { name: "NECSOM Technical Institute", industry: "Public Sectors", logo: "/clients/necsom-technical-institute-(nti).jpeg", country: "Somalia" },

    // Retailers & Wholesalers
    { name: "Ducaysane Supermarket", industry: "Retailers & Wholesalers", logo: "/clients/Ducaysane Supermarket retail.jpg", country: "Somalia" },
    { name: "Halaal", industry: "Retailers & Wholesalers", logo: "/clients/Halaal.jpeg", country: "Somalia" },
    { name: "Hargaisa Suite House Retail", industry: "Retailers & Wholesalers", logo: "/clients/Hargaisa suite house retail.png", country: "Somalia" },
    { name: "Horyaal Retail", industry: "Retailers & Wholesalers", logo: "/clients/Horyaal retail.png", country: "Somalia" },
    { name: "Carwo Isfahan Trade", industry: "Retailers & Wholesalers", logo: "/clients/carwo isfahan trade.png", country: "Somalia" },
    { name: "Oh Wooow Trade", industry: "Retailers & Wholesalers", logo: "/clients/oh wooow trade.jpg", country: "Somalia" },
    { name: "Bile General Trade", industry: "Retailers & Wholesalers", logo: "/clients/bile general trade.png", country: "Somalia" },
    { name: "Awaare Trade", industry: "Retailers & Wholesalers", logo: "/clients/Awaare trade.jpeg", country: "Somalia" },
    { name: "Mahdi Trade", industry: "Retailers & Wholesalers", logo: "/clients/mahdi  trade.jpeg", country: "Somalia" },
    { name: "Sunlight Trade", industry: "Retailers & Wholesalers", logo: "/clients/sunlight trade.jpg", country: "Somalia" },
    { name: "Hatta Computers", industry: "Retailers & Wholesalers", logo: "/clients/hatta computers.jpg", country: "Somalia" },
    { name: "Almadina Medicine Wholesaler", industry: "Retailers & Wholesalers", logo: "/clients/Almadina medicine wholeseler.jpeg", country: "Somalia" },
    { name: "Altowba Medicine Wholesaler", industry: "Retailers & Wholesalers", logo: "/clients/Altowba medicine whole eler.jpeg", country: "Somalia" },
    { name: "Ilays Medicine Wholesaler", industry: "Retailers & Wholesalers", logo: "/clients/Ilays medicine wholeseler.jpeg", country: "Somalia" },

    // General Services
    { name: "Amtel", industry: "General Services", logo: "/uploads/clients/amtel.png", country: "Somalia" },
    { name: "Telecommunication", industry: "General Services", logo: "/clients/telecommunication.jpg", country: "Somalia" },
    { name: "Cajiib Trade", industry: "General Services", logo: "/clients/cajiib trade.jpg", country: "Somalia" },
    { name: "GDG", industry: "General Services", logo: "/clients/GDG.jpeg", country: "Somalia" },
    { name: "GSG", industry: "General Services", logo: "/clients/GSG.jpg", country: "Somalia" },
    { name: "Miiqaat General Trade", industry: "General Services", logo: "/clients/miiqaad general trade.jpg", country: "Somalia" },
    { name: "One Trade", industry: "General Services", logo: "/clients/one trade .jpeg", country: "Somalia" },
    { name: "Saacid General Trading", industry: "General Services", logo: "/clients/Saacid General Trading.jpg", country: "Somalia" },
    { name: "Shire Food", industry: "General Services", logo: "/clients/shire food.png", country: "Somalia" },
    { name: "Mobile Fuundi", industry: "General Services", logo: "/clients/Mobile Fuundi.png", country: "Somalia" },
    { name: "Naafic Business", industry: "General Services", logo: "/clients/naafic business.jpg", country: "Somalia" },

    // Investment
    { name: "Amal Construction", industry: "Investment", logo: "/clients/Amal Construction.jpg", country: "Somalia" },
    { name: "Deryeel Construction", industry: "Investment", logo: "/clients/Deryeel construction.png", country: "Somalia" },
];
