
export const clientsData = [
    { name: "Amtel", industry: "Telecommunications", logo: "/clients/amtel.png" },
    { name: "Salaam Bank", industry: "Banking", logo: "/clients/salaam-bank.png" },
    { name: "LAWS", industry: "Water Supply", logo: "/clients/laws.png" },
    { name: "Arafat Hospital", industry: "Healthcare", logo: "/clients/arafat-hospital.png" },
    { name: "Amal Construction", industry: "Real Estate & Construction", logo: "/clients/amal-construction.png" },
    { name: "National Bank", industry: "Banking" },
    { name: "Somali Energy", industry: "Energy" },
    { name: "Global Tech", industry: "Technology" },
    { name: "Prime Retail", industry: "Retail" },
    { name: "Horizon Finance", industry: "Financial Services" },
    { name: "SafeHealth", industry: "Healthcare" },
    { name: "EcoLogistics", industry: "Logistics" },
    { name: "BuildSom", industry: "Construction" },
    { name: "AfroTrade", industry: "Trading" },
    { name: "SkyTelecom", industry: "Telecommunications" },
    { name: "Oceanic Shipping", industry: "Shipping" },
    { name: "Desert Oasis", industry: "Hospitality" },
    { name: "Nomad Motors", industry: "Automotive" },
    { name: "Pearl Gems", industry: "Mining" },
    { name: "Star Foundation", industry: "Non-Profit" },
    { name: "Unity Bank", industry: "Banking" },
    { name: "Solaris Power", industry: "Renewable Energy" },
    { name: "TechNova", industry: "Software" },
    { name: "MegaMart", industry: "Retail" },
    { name: "Vanguard Audit", industry: "Consulting" },
    { name: "MediCare Plus", industry: "Healthcare" },
    { name: "Express Cargo", industry: "Logistics" },
    { name: "Ironclad Const", industry: "Construction" },
    { name: "East Winds", industry: "Agriculture" },
    { name: "Vertex Mobile", industry: "Telecommunications" },
    { name: "Blue Water", industry: "Fisheries" },
    { name: "Royal Suites", industry: "Hospitality" },
    { name: "Z-Auto", industry: "Automotive" },
    { name: "DeepEarth", industry: "Mining" },
    { name: "Global Aid", industry: "NGO" },
    { name: "Pioneer Bank", industry: "Banking" },
    { name: "Volt Grid", industry: "Energy" },
    { name: "Silicon Sands", industry: "Technology" },
    { name: "Evergreen", industry: "Agriculture" },
    { name: "Alpha Capital", industry: "Investment" },
    { name: "MedLife", industry: "Healthcare" },
    { name: "Rapid Trail", industry: "Logistics" },
    { name: "Concrete Hub", industry: "Construction" },
    { name: "AgroPlus", industry: "Agriculture" },
    { name: "ConnectX", industry: "Telecommunications" },
    { name: "Silver Line", industry: "Shipping" },
    { name: "Grand Palace", industry: "Hospitality" },
    { name: "AutoMax", industry: "Automotive" },
    { name: "Gold Standard", industry: "Mining" },
    { name: "Heart 2 Heart", industry: "Charity" },
    { name: "Capital Trust", industry: "Banking" },
    { name: "PowerFlow", industry: "Energy" },
    { name: "NexGen", industry: "Technology" },
    { name: "Fresh Field", industry: "Agriculture" },
    { name: "Summit Partners", industry: "Consulting" },
];
